### ISSUE TITLE
sl3 behaves strange

### ISSUE THREAD

**Issue by kmpm** [opensounder/python-sllib#2]
There is either something wrong in the sl3 definition or in the test file.
They don't match up.

I would like to have some more sl3 files to test on.

**Comment by mdenbina** [comment]
I tried to load sl3 data using sllib, but seem to get errors, e.g., latitudes/longitudes of thousands of degrees and water depths on the order of 10^36 m.  If you are interested in having a copy of the sl3 file I am having trouble with I would be happy to send it, just let me know where.

**Comment by kmpm** [comment]
Sl3 definitely have some issues and I would love to have some more files to aid in the reverse engineering.
How big is it?
If it's less then 2GB you could use something like https://sprend.com for free. Less then 5 mb the just email to git@kmpm.se

**Comment by mdenbina** [comment]
It is about 65 MB, I just sent it with Sprend.  Thanks!

**Comment by kmpm** [comment]
Thanks for the file. I begun to check if I can figure out the sl3 format.

Is it ok to include the file in my public test data ( https://github.com/opensounder/sample-data-lowrance )? Or do you want to keep it secret?

**Comment by KennethTM** [comment]
Hi everyone

I have a very basic R-package (https://github.com/KennethTM/sonaR) that also aims to extract data from the sl2 and sl3 formats. 

The sl3 reader works on the test file that I have at least. Maybe it could provide some help on the byte positioning etc.? Link to read function as a very simple implementation in c++: https://github.com/KennethTM/sonaR/blob/master/src/read_slx.cpp line 181 to 281.

Kenneth

**Comment by kmpm** [comment]
@KennethTM, thanks I will have a look in a few days

**Comment by kmpm** [comment]
SL3 is now usable on format 3 version 1 and a huge thanks to @KennethTM  
The file from @mdenbina is unfortunately version 2 of the format and more investigation is needed..
If you run examples/tocvs.py on any sl3 file it will produce usable info from sl3 version 1, at least on the samples I have.

**Comment by kmpm** [comment]
Version 1 and 2 now works. There are some flags and fields that are missing but it's usable at least.
Thanks again

**Comment by mdenbina** [comment]
Hi Peter,

Thanks so much!  I just tested it and it works great.  And to reply to your
earlier e-mail, please feel free to include that file in your test data if
you would like.  Sorry for the slow reply, I didn't see these messages in
my inbox for some reason.  Thanks again for your help!  sl-lib has been
really useful for converting our sonar data.

Best,

Michael
