### ISSUE TITLE
read echograms

### ISSUE THREAD

**Issue by kmpm** [opensounder/python-sllib#4]
@stephenj79 wrote this in issue #3 but it deserves it's own

I think I have figured out the sounding data packet. I am assuming that it is a 1D profile of the received 'ping' energy, though I am only using a simple single source/receiver HDS5 sonar. I was under the impression that the vertical axis of each data sounding would be in time from ping to receiving, however it appears to be a sample interval in depth, that is a ratio of the 'lower_limit' parameter. Very strange, coming from a seismic background!

Below is a function to read the frame 'metadata' (for lack of better word) and the packet, and output them as a list of dicts and a numpy array, respectively. You can probably tell that this is a modification of the function given in the examples of this library. Probably not the best way to output the data (might be better to treat each packet as an array attached to the corresponding frame? Probably something for you guys to decide if you want to use this code), but gives an idea of how the data packet can be read:
```python
def read_echogram(input_file):
    import sllib
    with open(input_file, "rb") as f:
        reader = sllib.Reader(f)
        header = reader.header
        print(header)
        data = []
        for frame in reader:
            data.append(frame.to_dict())
            # the code to unpack the data packet
            temp = struct.unpack("i" * (frame.packetsize // 4), frame.packet)
            temp = np.array(temp)
            try:
                echogram = np.vstack((echogram, temp))
            except NameError:
                echogram = temp
    echogram = echogram.T.astype("float32")
    return data, echogram
```

Here's a function to read an sl2 file (using above function) and then plot the data packet numpy array as a matplotlib imshow, and overlay the automated water bottom pick. Comparing the output to this to what is shown in the software Sonar Viewer for the same file shows they are the same, which is what I was aiming for. But if you see any discrepancies, please let me know!

```python
def test_overlay_wb_echo(filename):
    import matplotlib.pyplot as plt
    # Load sounding data and echogram.
    data, echo = read_echogram(filename)
    ## Calculate sampling rate, using assumption that y-axis is in depth (ft)
    ## - not actually used in this function but given here as an illustration. 
    # time1 = np.array([i["time1"] for i in data])
    # dz = time1[1:] - time1[:-1]
    ## Calculate the water depth in y-axis samples
    wb = np.array([i["water_depth"] for i in data])
    lower_limit = np.array([i["lower_limit"] for i in data])
    wb_s =  wb * echo.shape[0] / lower_limit
    fig, axes = plt.subplots()
    axes.imshow(echo)
    axes.plot([i["frame_index"] for i in data],
                 wb_s, linewidth=2, color="red")
    fig.show()
```
I hope that helps. The code isn't the best, as I've been rushing to get it working for a job, so please excuse anything that looks bad. For example the "try / except" in the read function is pretty shoddy, but it meant I got the code working, fast.

Looking forward to some feedback.

Kind regards,
Steve

**Comment by kmpm** [comment]
Attaching output from a jupyter notebook trying to do this.
[read_echogram.pdf](https://github.com/opensounder/python-sllib/files/5459201/read_echogram.pdf)

The output from the sample `small.sl2` would look like this.
![output_4_1](https://user-images.githubusercontent.com/96618/97590146-9b21c000-19fe-11eb-9a7f-3855cd99dcaf.png)

**Comment by NicholasBallard** [comment]
@kmpm Thanks for implementing this!

**Comment by kmpm** [comment]
echogram reading examples moved to https://github.com/opensounder/python-sllib
