### ISSUE TITLE
Malformed values after converting slg to csv

### ISSUE THREAD

**Issue by anteksz24** [opensounder/python-sllib#5]
After converting SLG file to CSV the values are completely distorted and inaccurate. 
![obraz](https://user-images.githubusercontent.com/81700084/116356345-723a8600-a7fb-11eb-8d7d-56187f6c1cc0.png)

**Comment by tarinishukla** [comment]
You can try SonarLogApi. It works.

**Comment by kmpm** [comment]
slg, or in fact the whole library is very much a work in progress at the moment so major errors is probably expected.
And since I don't have anything that can produce slg files I'm in extra bad shape and lack of interest of slg but it will happen.

**Comment by kmpm** [comment]
SonarLogApi (the version I found) doesn't even implement slg.
```csharp
   ...
   case FileVersion.SLG:
     throw new NotImplementedException();
   ...
```
